kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-route
spec:
  to:
    kind: Service
    name: myrelease-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None