apiVersion: v1
kind: Service
metadata:
  name: release-name-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: release-name-pod
