name: CI

on: [push, workflow_dispatch]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t my-app .

      - name: Run app in container and tests
        run: |
          docker run -d -p 8080:8080 my-app &
          sleep 10  # Wait for the app to be up and running
          coverage run -m unittest discover
          coverage report -m
          docker stop $(docker ps -q --filter ancestor=my-app)
