name: Greeting Workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Greeting list'
        required: true
        default: 'warning'
        type: choice
        options:
        - Good morning
        - Good afternoon
        - Good evening
        - Good night
      from-flask:
        description: 'from flask checkbox'
        required: false
        type: boolean
      environment:
        description: 'GitHub Environment list'
        type: environment
        required: true

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo "${{ inputs.greeting }} from flask: [${{ inputs.from-flask }}] in GitHub ${{ inputs.environment }} env !"